INSERT INTO STUDENT(NAME, SCIENCE, MATH, HISTORY) VALUES("tony",12,12,12);
INSERT INTO STUDENT(NAME, SCIENCE, MATH, HISTORY) VALUES("antony",13,13,13);
INSERT INTO STUDENT(NAME, SCIENCE, MATH, HISTORY) VALUES("bantony",14,14,14);
